@baseUrl = http://localhost:8080/api

### 0. initalize note id → save {{noteId}}
GET {{baseUrl}}/notebook

> {%
    client.global.set("noteId", response.body.body[0].id);
%}

### 1. list conversations
GET {{baseUrl}}/notes/{{noteId}}/conversations

### 2. create conversation  → save {{conversationId}}
POST {{baseUrl}}/notes/{{noteId}}/conversations
Content-Type: application/json

{
  "title": "test"
}

> {%
    client.global.set("conversationId", response.body.body.id);
%}

### 3. get a conversation
GET {{baseUrl}}/notes/{{noteId}}/conversations/{{conversationId}}

### 4. list messages
GET {{baseUrl}}/notes/{{noteId}}/conversations/{{conversationId}}/messages

### 5. delete conversation
DELETE {{baseUrl}}/notes/{{noteId}}/conversations/{{conversationId}}

GET {{baseUrl}}/notes/{{noteId}}/conversations
